consolidated with other projects;

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,8 +7,46 @@ on:
     tags:
       - '*'
 
+env:
+  RELEASE: 4.2.0.21
+
 jobs:
+  build-test:
+    name: Build & Run tests
+    runs-on: ubuntu-22.04
+
+    steps:
+      - uses: actions/checkout@v2                                 # checkout the repo
+
+      - name: Install qmltestrunner                               # install required qmltestrunner packages
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y qtdeclarative5-dev-tools qml-module-qtquick-localstorage
+          sudo apt-get install -y qml-module-qtquick-controls qml-module-qttest qt5-qmake
+          sudo apt-get install -y libqt5test5 qtbase5-dev qtdeclarative5-dev
+
+      - name: Run QML / C++ Tests
+        run: |
+          set -x
+          # cd test/qml 
+          # ./runTests.sh
+          # ./fixJunit.sh
+          # cd ..                                                   
+          cd test/cpp
+          # sudo timedatectl set-timezone Europe/Berlin
+          ./runTests.sh
+          ./fixJunit.sh
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1.6.0
+        if: success() || failure()                                # run this step even if previous step failed
+        with:
+          name: QML/C++ Tests                                     # Name of the check run which will be created
+          path: test/qml/*.xml,test/cpp/*.xml                     # Path to test results
+          reporter: jest-junit                                    # Format of test results - because junit cannot be generated
+
   build:
+    name: Build & Package
     runs-on: ubuntu-latest
 
     steps:
@@ -18,37 +56,44 @@ jobs:
         run: mkdir output
 
       - name: Build armv7hl
-        id: build_armv7hl
-        uses: coderus/github-sfos-build@master
-        with:
-          release: 3.4.0.24
+        run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
+          cd /home/mersdk ;
+          mkdir -p build ;
+          cd build ;
+          cp -r /share/* . ;
+          mb2 -t SailfishOS-$RELEASE-armv7hl build ;
+          sudo cp -r RPMS/*.rpm /share/output"
 
       - name: Build i486
-        id: build_i486
-        uses: coderus/github-sfos-build@master
-        with:
-          release: 3.4.0.24
-          arch: i486
+        run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
+          cd /home/mersdk ;
+          mkdir -p build ;
+          cd build ;
+          cp -r /share/* . ;
+          mb2 -t SailfishOS-$RELEASE-i486 build ;
+          sudo cp -r RPMS/*.rpm /share/output"
 
       - name: Build aarch64
-        id: build_aarch64
-        uses: coderus/github-sfos-build@master
-        with:
-          release: 4.0.1.45
-          arch: aarch64
+        run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
+          cd /home/mersdk ;
+          mkdir -p build ;
+          cd build ;
+          cp -r /share/* . ;
+          mb2 -t SailfishOS-$RELEASE-aarch64 build ;
+          sudo cp -r RPMS/*.rpm /share/output"
 
       - name: Upload build result
         uses: actions/upload-artifact@v2
         with:
-          name: rpm-build-result
-          path: RPMS
+          name: output-rpms
+          path: output
 
       - name: Create release
         if: contains(github.ref, 'release')
         run: |
           set -x
           assets=()
-          for asset in RPMS/*.rpm; do
+          for asset in output/*.rpm; do
             assets+=("-a" "$asset")
           done
           tag_name="${GITHUB_REF##*/}"
